# Generated by Django 4.0.2 on 2022-09-10 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('point', models.CharField(choices=[('1', 'very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'very Good')], max_length=10)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('datetime_edit', models.DateTimeField(auto_now=True)),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
