# Generated by Django 4.0.2 on 2022-09-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Products',
            new_name='products',
        ),
    ]
