# Generated by Django 4.0.2 on 2022-10-09 12:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_product_datetime_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shor_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ساخت نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='ویرایش نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.CharField(choices=[('1', 'very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'very Good')], max_length=10, verbose_name='چه امتیازی میدهید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ساخت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/product_cover', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
